environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:

  - "%PYTHON%\\python.exe -m pip install requests"

build: off

test_script:
  #- "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:

  - "%PYTHON%\\python.exe setup.py install"

artifacts:

  - path: dist\*

#on_success:

